# Generated by Django 4.2.1 on 2023-05-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction", old_name="timestamp", new_name="date",
        ),
        migrations.AddField(
            model_name="transaction",
            name="decription",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
